/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Semana7RouteImport } from './routes/semana-7'
import { Route as Semana6RouteImport } from './routes/semana-6'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as Modulo3RouteImport } from './routes/modulo-3'
import { Route as Modulo2RouteImport } from './routes/modulo-2'
import { Route as Modulo1RouteImport } from './routes/modulo-1'
import { Route as JuegosRouteImport } from './routes/juegos'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as IndexRouteImport } from './routes/index'

const Semana7Route = Semana7RouteImport.update({
  id: '/semana-7',
  path: '/semana-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Semana6Route = Semana6RouteImport.update({
  id: '/semana-6',
  path: '/semana-6',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo3Route = Modulo3RouteImport.update({
  id: '/modulo-3',
  path: '/modulo-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo2Route = Modulo2RouteImport.update({
  id: '/modulo-2',
  path: '/modulo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo1Route = Modulo1RouteImport.update({
  id: '/modulo-1',
  path: '/modulo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosRoute = JuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingresar'
    | '/juegos'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/semana-6'
    | '/semana-7'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingresar'
    | '/juegos'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/semana-6'
    | '/semana-7'
  id:
    | '__root__'
    | '/'
    | '/ingresar'
    | '/juegos'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/semana-6'
    | '/semana-7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngresarRoute: typeof IngresarRoute
  JuegosRoute: typeof JuegosRoute
  Modulo1Route: typeof Modulo1Route
  Modulo2Route: typeof Modulo2Route
  Modulo3Route: typeof Modulo3Route
  PanelRoute: typeof PanelRoute
  ProyectoRoute: typeof ProyectoRoute
  Semana6Route: typeof Semana6Route
  Semana7Route: typeof Semana7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana-7': {
      id: '/semana-7'
      path: '/semana-7'
      fullPath: '/semana-7'
      preLoaderRoute: typeof Semana7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana-6': {
      id: '/semana-6'
      path: '/semana-6'
      fullPath: '/semana-6'
      preLoaderRoute: typeof Semana6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-3': {
      id: '/modulo-3'
      path: '/modulo-3'
      fullPath: '/modulo-3'
      preLoaderRoute: typeof Modulo3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-2': {
      id: '/modulo-2'
      path: '/modulo-2'
      fullPath: '/modulo-2'
      preLoaderRoute: typeof Modulo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-1': {
      id: '/modulo-1'
      path: '/modulo-1'
      fullPath: '/modulo-1'
      preLoaderRoute: typeof Modulo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos': {
      id: '/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof JuegosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngresarRoute: IngresarRoute,
  JuegosRoute: JuegosRoute,
  Modulo1Route: Modulo1Route,
  Modulo2Route: Modulo2Route,
  Modulo3Route: Modulo3Route,
  PanelRoute: PanelRoute,
  ProyectoRoute: ProyectoRoute,
  Semana6Route: Semana6Route,
  Semana7Route: Semana7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
