/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorIaRouteImport } from './routes/tutor-ia'
import { Route as Semana7RouteImport } from './routes/semana-7'
import { Route as Semana6RouteImport } from './routes/semana-6'
import { Route as PruebaDiagnosticaRouteImport } from './routes/prueba-diagnostica'
import { Route as ProyectoLecturaRouteImport } from './routes/proyecto-lectura'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as Modulo3RouteImport } from './routes/modulo-3'
import { Route as Modulo2RouteImport } from './routes/modulo-2'
import { Route as Modulo1RouteImport } from './routes/modulo-1'
import { Route as LecturaAdaptativaRouteImport } from './routes/lectura-adaptativa'
import { Route as LecturaRouteImport } from './routes/lectura'
import { Route as JuegosRouteImport } from './routes/juegos'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as EvaluacionFormativaRouteImport } from './routes/evaluacion-formativa'
import { Route as DiagnosticoLecturaRouteImport } from './routes/diagnostico-lectura'
import { Route as IndexRouteImport } from './routes/index'

const TutorIaRoute = TutorIaRouteImport.update({
  id: '/tutor-ia',
  path: '/tutor-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const Semana7Route = Semana7RouteImport.update({
  id: '/semana-7',
  path: '/semana-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Semana6Route = Semana6RouteImport.update({
  id: '/semana-6',
  path: '/semana-6',
  getParentRoute: () => rootRouteImport,
} as any)
const PruebaDiagnosticaRoute = PruebaDiagnosticaRouteImport.update({
  id: '/prueba-diagnostica',
  path: '/prueba-diagnostica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoLecturaRoute = ProyectoLecturaRouteImport.update({
  id: '/proyecto-lectura',
  path: '/proyecto-lectura',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo3Route = Modulo3RouteImport.update({
  id: '/modulo-3',
  path: '/modulo-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo2Route = Modulo2RouteImport.update({
  id: '/modulo-2',
  path: '/modulo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo1Route = Modulo1RouteImport.update({
  id: '/modulo-1',
  path: '/modulo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturaAdaptativaRoute = LecturaAdaptativaRouteImport.update({
  id: '/lectura-adaptativa',
  path: '/lectura-adaptativa',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturaRoute = LecturaRouteImport.update({
  id: '/lectura',
  path: '/lectura',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosRoute = JuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionFormativaRoute = EvaluacionFormativaRouteImport.update({
  id: '/evaluacion-formativa',
  path: '/evaluacion-formativa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoLecturaRoute = DiagnosticoLecturaRouteImport.update({
  id: '/diagnostico-lectura',
  path: '/diagnostico-lectura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostico-lectura': typeof DiagnosticoLecturaRoute
  '/evaluacion-formativa': typeof EvaluacionFormativaRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/lectura': typeof LecturaRoute
  '/lectura-adaptativa': typeof LecturaAdaptativaRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/proyecto-lectura': typeof ProyectoLecturaRoute
  '/prueba-diagnostica': typeof PruebaDiagnosticaRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
  '/tutor-ia': typeof TutorIaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostico-lectura': typeof DiagnosticoLecturaRoute
  '/evaluacion-formativa': typeof EvaluacionFormativaRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/lectura': typeof LecturaRoute
  '/lectura-adaptativa': typeof LecturaAdaptativaRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/proyecto-lectura': typeof ProyectoLecturaRoute
  '/prueba-diagnostica': typeof PruebaDiagnosticaRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
  '/tutor-ia': typeof TutorIaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostico-lectura': typeof DiagnosticoLecturaRoute
  '/evaluacion-formativa': typeof EvaluacionFormativaRoute
  '/ingresar': typeof IngresarRoute
  '/juegos': typeof JuegosRoute
  '/lectura': typeof LecturaRoute
  '/lectura-adaptativa': typeof LecturaAdaptativaRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/modulo-3': typeof Modulo3Route
  '/panel': typeof PanelRoute
  '/proyecto': typeof ProyectoRoute
  '/proyecto-lectura': typeof ProyectoLecturaRoute
  '/prueba-diagnostica': typeof PruebaDiagnosticaRoute
  '/semana-6': typeof Semana6Route
  '/semana-7': typeof Semana7Route
  '/tutor-ia': typeof TutorIaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostico-lectura'
    | '/evaluacion-formativa'
    | '/ingresar'
    | '/juegos'
    | '/lectura'
    | '/lectura-adaptativa'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/proyecto-lectura'
    | '/prueba-diagnostica'
    | '/semana-6'
    | '/semana-7'
    | '/tutor-ia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostico-lectura'
    | '/evaluacion-formativa'
    | '/ingresar'
    | '/juegos'
    | '/lectura'
    | '/lectura-adaptativa'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/proyecto-lectura'
    | '/prueba-diagnostica'
    | '/semana-6'
    | '/semana-7'
    | '/tutor-ia'
  id:
    | '__root__'
    | '/'
    | '/diagnostico-lectura'
    | '/evaluacion-formativa'
    | '/ingresar'
    | '/juegos'
    | '/lectura'
    | '/lectura-adaptativa'
    | '/modulo-1'
    | '/modulo-2'
    | '/modulo-3'
    | '/panel'
    | '/proyecto'
    | '/proyecto-lectura'
    | '/prueba-diagnostica'
    | '/semana-6'
    | '/semana-7'
    | '/tutor-ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticoLecturaRoute: typeof DiagnosticoLecturaRoute
  EvaluacionFormativaRoute: typeof EvaluacionFormativaRoute
  IngresarRoute: typeof IngresarRoute
  JuegosRoute: typeof JuegosRoute
  LecturaRoute: typeof LecturaRoute
  LecturaAdaptativaRoute: typeof LecturaAdaptativaRoute
  Modulo1Route: typeof Modulo1Route
  Modulo2Route: typeof Modulo2Route
  Modulo3Route: typeof Modulo3Route
  PanelRoute: typeof PanelRoute
  ProyectoRoute: typeof ProyectoRoute
  ProyectoLecturaRoute: typeof ProyectoLecturaRoute
  PruebaDiagnosticaRoute: typeof PruebaDiagnosticaRoute
  Semana6Route: typeof Semana6Route
  Semana7Route: typeof Semana7Route
  TutorIaRoute: typeof TutorIaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor-ia': {
      id: '/tutor-ia'
      path: '/tutor-ia'
      fullPath: '/tutor-ia'
      preLoaderRoute: typeof TutorIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana-7': {
      id: '/semana-7'
      path: '/semana-7'
      fullPath: '/semana-7'
      preLoaderRoute: typeof Semana7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana-6': {
      id: '/semana-6'
      path: '/semana-6'
      fullPath: '/semana-6'
      preLoaderRoute: typeof Semana6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prueba-diagnostica': {
      id: '/prueba-diagnostica'
      path: '/prueba-diagnostica'
      fullPath: '/prueba-diagnostica'
      preLoaderRoute: typeof PruebaDiagnosticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-lectura': {
      id: '/proyecto-lectura'
      path: '/proyecto-lectura'
      fullPath: '/proyecto-lectura'
      preLoaderRoute: typeof ProyectoLecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-3': {
      id: '/modulo-3'
      path: '/modulo-3'
      fullPath: '/modulo-3'
      preLoaderRoute: typeof Modulo3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-2': {
      id: '/modulo-2'
      path: '/modulo-2'
      fullPath: '/modulo-2'
      preLoaderRoute: typeof Modulo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-1': {
      id: '/modulo-1'
      path: '/modulo-1'
      fullPath: '/modulo-1'
      preLoaderRoute: typeof Modulo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectura-adaptativa': {
      id: '/lectura-adaptativa'
      path: '/lectura-adaptativa'
      fullPath: '/lectura-adaptativa'
      preLoaderRoute: typeof LecturaAdaptativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectura': {
      id: '/lectura'
      path: '/lectura'
      fullPath: '/lectura'
      preLoaderRoute: typeof LecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos': {
      id: '/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof JuegosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluacion-formativa': {
      id: '/evaluacion-formativa'
      path: '/evaluacion-formativa'
      fullPath: '/evaluacion-formativa'
      preLoaderRoute: typeof EvaluacionFormativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-lectura': {
      id: '/diagnostico-lectura'
      path: '/diagnostico-lectura'
      fullPath: '/diagnostico-lectura'
      preLoaderRoute: typeof DiagnosticoLecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticoLecturaRoute: DiagnosticoLecturaRoute,
  EvaluacionFormativaRoute: EvaluacionFormativaRoute,
  IngresarRoute: IngresarRoute,
  JuegosRoute: JuegosRoute,
  LecturaRoute: LecturaRoute,
  LecturaAdaptativaRoute: LecturaAdaptativaRoute,
  Modulo1Route: Modulo1Route,
  Modulo2Route: Modulo2Route,
  Modulo3Route: Modulo3Route,
  PanelRoute: PanelRoute,
  ProyectoRoute: ProyectoRoute,
  ProyectoLecturaRoute: ProyectoLecturaRoute,
  PruebaDiagnosticaRoute: PruebaDiagnosticaRoute,
  Semana6Route: Semana6Route,
  Semana7Route: Semana7Route,
  TutorIaRoute: TutorIaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
